### ISSUE TITLE
alpine image very large

### ISSUE THREAD

**Issue by AlJohri** [Linuxbrew/docker#67]
It seems like the alpine image is one of the largest. It might be worth noting this in the README for users who expect alpine to be the smallest image:

```
linuxbrew/brew      latest              fc68ca22ec7e        5 hours ago          559MB
linuxbrew/debian    latest              881c478b7622        22 hours ago         447MB
linuxbrew/alpine    latest              10ca6eb17d94        22 hours ago         954MB
```

**Comment by sjackman** [comment]
Yeah, that's because it has to jump through a bunch of hoops to install `glibc`, since Alpine Linux doesn't include `glibc`, and so it ends up installing a number of dependencies like `ruby` and `gcc` using both `apk` and `gcc`. The size of the image could be reduced by combining both `RUN` statements into a single `RUN` statement, and removing the packages installed using `apk` after the system is bootstrapped, as well as removing `~/.cache` and the `apk` cache if there is one.

@AlJohri Are you interested in working on that?

**Comment by AlJohri** [comment]
Sure thing, I can give it a shot. I don't fully understand what's going on in the Dockerfile but I can definitely do those steps you outlined above.

**Comment by sjackman** [comment]
Great! Feel free to submit a PR of your work in progress if you have any questions.
